version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    build:
      context: . 
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    restart: always  

    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
    