name: Deploy restapiflask

on:
  push:
    branches: [main]

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
         flake8 pytest mongomock

      - name: Run tests
      - run: make test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Deploy to heroku
        run: make heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


